### PR TITLE
fix docker multistage build error

### PR DESCRIPTION
**Pull request by levinxo**

### CODE REVIEW

**Comment by levinxo** [comment]
ping @jbkyang-nvi

**Comment by jbkyang-nvi** [comment]
Thanks for your contribution. Can you refer to https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md and send a [CLA](https://github.com/triton-inference-server/server/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla)

**Comment by jbkyang-nvi** [comment]
I'm fixing this in https://github.com/triton-inference-server/fastertransformer_backend/pull/158 (alongside other changes)

**Comment by levinxo** [comment]
okk, close it.

**Pull request closed without merging**
